version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - GEMINI_API_KEY=your_real_gemini_key
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - FLASK_API_URL=http://backend:5000
    depends_on:
      - backend
    restart: unless-stopped
